default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_telegram_development

test:
  <<: *default
  database: rails_telegram_test

production:
  <<: *default
  database: rails_telegram_production
  username: rails_telegram
  password: <%= ENV['RAILS_TELEGRAM_DATABASE_PASSWORD'] %>
